spring:
  datasource:
    hikari:
      auto-commit: false #connection 이 종료되거나 pool에 반환될때, connection에 속해 있는 transaction을 commit 할지 결정한다. (default: true)
      connection-test-query: select 1 from dual
      connection-timeout: 60000 # (default: 600000 - 10 minutes) connection pool에 의하여 확보된 connection의 최대 생명주기를 지정합니다.
      maximum-pool-size: 30
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@(DESCRIPTION=(LOAD_BALANCE=on)(ADDRESS=(PROTOCOL=TCP)(HOST=172.31.165.51) (PORT=1527))(ADDRESS=(PROTOCOL=TCP)(HOST=172.31.165.51) (PORT=1528))(ADDRESS=(PROTOCOL=TCP)(HOST=172.31.165.51) (PORT=1529))(ADDRESS=(PROTOCOL=TCP)(HOST=172.31.165.53) (PORT=1527))(ADDRESS=(PROTOCOL=TCP)(HOST=172.31.165.53) (PORT=1528))(ADDRESS=(PROTOCOL=TCP)(HOST=172.31.165.53) (PORT=1529))(CONNECT_DATA=(SERVICE_NAME=SWGMSAP)))
    username: ${MSA_MC_USER}
    password: ${MSA_MC_PASSWORD}    


  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    open-in-view: false
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false  
    show-sql: false
    properties:
      hibernate.enable_lazy_load_no_trans: true
      hibernate.use_sql_comments: true
      hibernate.format_sql: true